name: Build
on:
  push:
    paths-ignore:
      - .editorconfig
      - .gitattributes
      - README.md
      - LICENSE
      - LICENSE_fabric-mod-loader
      - .gitignore
      - HEADER
      - src/main/resources
      - minecraft/src/main/resources
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: 8 # FCWorkgroupMC - modlauncher 8 only targets Java 8
          distribution: temurin
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew clean build --no-daemon
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
